baseURL: https://blog.tanaka.world
languageCode: ja
title: For X Developers
theme: PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-122034388-1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: For X Developers
  description: Memorandom for me and "X" developers in the world.
  # author: tanakaworld

  images: ["/cover.jpg"]

  ShowReadingTime: false
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    # disableHLJS: true # to disable highlightjs
    # disableFingerprinting: true
    favicon: /favicon.png
    favicon16x16: /favicon.png
    favicon32x32: /favicon.png
    apple_touch_icon: /favicon.png
    safari_pinned_tab: /favicon.png

  label:
    text: "For X Developer"
    icon: /favicon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi there 👋️"
    Content:
      This is the memorandom for me and "X" developers in the world.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/_tanakaworld"
    - name: github
      url: "https://github.com/tanakaworld"
    - name: RSS
      url: "index.xml"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Author
      name: Author
      url: https://tanaka.world/
      weight: 30
    - identifier: RSS
      name: RSS
      url: /index.xml
      weight: 30

permalinks:
  posts: /:slug/

markup:
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

defaultContentLanguage: ja
languages:
  ja:
    weight: 1
    languageName: Japanese
  en:
    weight: 2
    languageName: English
